### ISSUE TITLE
Specify default npm version

### ISSUE THREAD

**Issue by Copser** [Oefenweb/ansible-nodejs#11]
Hey, I started using your nodejs and it's awesome. I have a question regarding npm version, so is there a way to specify which npm version I can install, I suppose it will go in `defaults/main.yml`. 

```
# defaults file for nodejs
---
nodejs_version: 'nodejs-v8x'
npm_version: 'npm-6.0.0.' - is this possible
```

Thanks.

**Comment by tersmitten** [comment]
You can use the `nodejs_npm_packages` variable, [see](https://github.com/Oefenweb/ansible-nodejs/blob/master/tests/test.yml#L13).

Something like this?

```yml
    nodejs_npm_packages:
      - name: npm
        version: 6.0.0
```
