### ISSUE TITLE
Installing package.json

### ISSUE THREAD

**Issue by Copser** [Oefenweb/ansible-nodejs#14]
Hey,

have a small question, is there a way that I can say `npm` to install `package.json`. I know I can just write down packages in `defaults/main.yml` for example:

```
nodejs_npm_packages:
  - name: angular-animation
    varsion: 6.0.7
  - name: angular-cdk
    version: 6.4.7
  - name: angular-cli
    version: 6.0.8
  - name: angular-common
    version: 6.0.7
  - name: angular-compiler
    version: angular-flex-layout
  - name: angular-forms
    version: 6.0.7
```
and it's fine, but is there a way that I just install `package.json`

Thanks.
