### ISSUE TITLE
Nodejs doesnt install the new version when you change the version number

### ISSUE THREAD

**Issue by lelandcope** [Oefenweb/ansible-nodejs#6]
When I change the version number and run my playbook again it doesnt seem to install the new version of Nodejs that I want? Is it possible to have it do this?

**Comment by tersmitten** [comment]
Probably, but that would make the role (much) more complex. Because that would involve removing files from `/etc/apt/sources.d/`. And I also don't know if downgrading nodejs would even work.

This is what I did in a local vagrant to upgrade from 0.10 to 4.x (manually):

```
  pre_tasks:
    - name: find old nodejs ppa
      shell: "grep --files-without-match node_4.x /etc/apt/sources.list.d/nodesource.list*"
      register: old_nodejs_ppa
      changed_when: false
      failed_when: false

    - name: remove nodejs ppa
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ old_nodejs_ppa.stdout_lines }}"
```

Can you verify that downgrading also works using the method above?
